# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(352, 394)
        MainWindow.setStyleSheet("background-color: rgb(85, 0, 0);\n"
"background-color: rgb(12, 12, 12);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.push_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_9.sizePolicy().hasHeightForWidth())
        self.push_9.setSizePolicy(sizePolicy)
        self.push_9.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_9.setObjectName("push_9")
        self.gridLayout.addWidget(self.push_9, 8, 2, 1, 1)
        self.push_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_5.sizePolicy().hasHeightForWidth())
        self.push_5.setSizePolicy(sizePolicy)
        self.push_5.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_5.setObjectName("push_5")
        self.gridLayout.addWidget(self.push_5, 7, 1, 1, 1)
        self.push_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_7.sizePolicy().hasHeightForWidth())
        self.push_7.setSizePolicy(sizePolicy)
        self.push_7.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_7.setObjectName("push_7")
        self.gridLayout.addWidget(self.push_7, 8, 0, 1, 1)
        self.push_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_2.sizePolicy().hasHeightForWidth())
        self.push_2.setSizePolicy(sizePolicy)
        self.push_2.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_2.setObjectName("push_2")
        self.gridLayout.addWidget(self.push_2, 6, 1, 1, 1)
        self.push_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_3.sizePolicy().hasHeightForWidth())
        self.push_3.setSizePolicy(sizePolicy)
        self.push_3.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_3.setObjectName("push_3")
        self.gridLayout.addWidget(self.push_3, 6, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 75 26pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.push_sub = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_sub.sizePolicy().hasHeightForWidth())
        self.push_sub.setSizePolicy(sizePolicy)
        self.push_sub.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(255, 196, 102);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(45, 45, 45);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_sub.setIconSize(QtCore.QSize(29, 23))
        self.push_sub.setObjectName("push_sub")
        self.gridLayout.addWidget(self.push_sub, 6, 3, 1, 1)
        self.push_add = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_add.sizePolicy().hasHeightForWidth())
        self.push_add.setSizePolicy(sizePolicy)
        self.push_add.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(255, 196, 102);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(45, 45, 45);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_add.setIconSize(QtCore.QSize(23, 36))
        self.push_add.setObjectName("push_add")
        self.gridLayout.addWidget(self.push_add, 1, 3, 1, 1)
        self.push_del = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_del.sizePolicy().hasHeightForWidth())
        self.push_del.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_del.setFont(font)
        self.push_del.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_del.setObjectName("push_del")
        self.gridLayout.addWidget(self.push_del, 1, 2, 1, 1)
        self.push_mul = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_mul.sizePolicy().hasHeightForWidth())
        self.push_mul.setSizePolicy(sizePolicy)
        self.push_mul.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(255, 196, 102);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(45, 45, 45);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_mul.setIconSize(QtCore.QSize(19, 24))
        self.push_mul.setObjectName("push_mul")
        self.gridLayout.addWidget(self.push_mul, 7, 3, 1, 1)
        self.push_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_1.sizePolicy().hasHeightForWidth())
        self.push_1.setSizePolicy(sizePolicy)
        self.push_1.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_1.setObjectName("push_1")
        self.gridLayout.addWidget(self.push_1, 6, 0, 1, 1)
        self.push_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_0.sizePolicy().hasHeightForWidth())
        self.push_0.setSizePolicy(sizePolicy)
        self.push_0.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_0.setObjectName("push_0")
        self.gridLayout.addWidget(self.push_0, 9, 0, 1, 2)
        self.push_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_clear.sizePolicy().hasHeightForWidth())
        self.push_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.push_clear.setFont(font)
        self.push_clear.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(221,40,16);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(221,40,16);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    \n"
"    background-color: rgb(33, 33, 33);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_clear.setObjectName("push_clear")
        self.gridLayout.addWidget(self.push_clear, 1, 0, 1, 2)
        self.push_equal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_equal.sizePolicy().hasHeightForWidth())
        self.push_equal.setSizePolicy(sizePolicy)
        self.push_equal.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(255, 196, 102);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(45, 45, 45);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_equal.setIconSize(QtCore.QSize(20, 18))
        self.push_equal.setObjectName("push_equal")
        self.gridLayout.addWidget(self.push_equal, 9, 3, 1, 1)
        self.push_dot = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_dot.sizePolicy().hasHeightForWidth())
        self.push_dot.setSizePolicy(sizePolicy)
        self.push_dot.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_dot.setObjectName("push_dot")
        self.gridLayout.addWidget(self.push_dot, 9, 2, 1, 1)
        self.push_div = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_div.sizePolicy().hasHeightForWidth())
        self.push_div.setSizePolicy(sizePolicy)
        self.push_div.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(255, 196, 102);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(45, 45, 45);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_div.setIconSize(QtCore.QSize(21, 25))
        self.push_div.setObjectName("push_div")
        self.gridLayout.addWidget(self.push_div, 8, 3, 1, 1)
        self.push_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_4.sizePolicy().hasHeightForWidth())
        self.push_4.setSizePolicy(sizePolicy)
        self.push_4.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_4.setObjectName("push_4")
        self.gridLayout.addWidget(self.push_4, 7, 0, 1, 1)
        self.push_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_6.sizePolicy().hasHeightForWidth())
        self.push_6.setSizePolicy(sizePolicy)
        self.push_6.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_6.setObjectName("push_6")
        self.gridLayout.addWidget(self.push_6, 7, 2, 1, 1)
        self.push_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push_8.sizePolicy().hasHeightForWidth())
        self.push_8.setSizePolicy(sizePolicy)
        self.push_8.setStyleSheet("QPushButton{ \n"
"    font: 75 26pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(148, 148, 148);\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(57, 57, 57);\n"
"    background-color: rgb(130, 180, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(27, 27, 27);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.push_8.setObjectName("push_8")
        self.gridLayout.addWidget(self.push_8, 8, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 352, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.push_1.clicked.connect(self.method_1)
        self.push_2.clicked.connect(self.method_2)
        self.push_3.clicked.connect(self.method_3)
        self.push_4.clicked.connect(self.method_4)
        self.push_5.clicked.connect(self.method_5)
        self.push_6.clicked.connect(self.method_6)
        self.push_7.clicked.connect(self.method_7)
        self.push_8.clicked.connect(self.method_8)
        self.push_9.clicked.connect(self.method_9)
        self.push_0.clicked.connect(self.method_0)
        self.push_sub.clicked.connect(self.method_sub)
        self.push_add.clicked.connect(self.method_add)
        self.push_div.clicked.connect(self.method_div)
        self.push_mul.clicked.connect(self.method_mul)
        self.push_del.clicked.connect(self.method_del)
        self.push_clear.clicked.connect(self.method_clear)
        self.push_equal.clicked.connect(self.method_equal)
        self.push_dot.clicked.connect(self.method_dot)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.push_9.setText(_translate("MainWindow", "9"))
        self.push_5.setText(_translate("MainWindow", "5"))
        self.push_7.setText(_translate("MainWindow", "7"))
        self.push_2.setText(_translate("MainWindow", "2"))
        self.push_3.setText(_translate("MainWindow", "3"))
        self.label.setText(_translate("MainWindow", "0"))
        self.push_sub.setText(_translate("MainWindow", "-"))
        self.push_add.setText(_translate("MainWindow", "+"))
        self.push_del.setText(_translate("MainWindow", "DEL"))
        self.push_mul.setText(_translate("MainWindow", "x"))
        self.push_1.setText(_translate("MainWindow", "1"))
        self.push_0.setText(_translate("MainWindow", "0"))
        self.push_clear.setText(_translate("MainWindow", "Clear"))
        self.push_equal.setText(_translate("MainWindow", "="))
        self.push_dot.setText(_translate("MainWindow", "."))
        self.push_div.setText(_translate("MainWindow", "÷"))
        self.push_4.setText(_translate("MainWindow", "4"))
        self.push_6.setText(_translate("MainWindow", "6"))
        self.push_8.setText(_translate("MainWindow", "8"))
        
    def method_1(self):
        text=self.label.text()
        self.label.setText(text+"1")
    def method_2(self):
        text=self.label.text()
        self.label.setText(text+"2")
    def method_3(self):
        text=self.label.text()
        self.label.setText(text+"3")
    def method_4(self):
        text=self.label.text()
        self.label.setText(text+"4")
    def method_5(self):
        text=self.label.text()
        self.label.setText(text+"5")
    def method_6(self):
        text=self.label.text()
        self.label.setText(text+"6")
    def method_7(self):
        text=self.label.text()
        self.label.setText(text+"7")
    def method_8(self):
        text=self.label.text()
        self.label.setText(text+"8")
    def method_9(self):
        text=self.label.text()
        self.label.setText(text+"9")
    def method_0(self):
        text=self.label.text()
        self.label.setText(text+"0")
    def method_sub(self):
        text=self.label.text()
        self.label.setText(text+"-")
    def method_add(self):
        text=self.label.text()
        self.label.setText(text+"+")
    def method_mul(self):
        text=self.label.text()
        self.label.setText(text+"*")
    def method_div(self):
        text=self.label.text()
        self.label.setText(text+"/")
    def method_equal(self):
        text=self.label.text()
        try:
            ans=eval(text)
            self.label.setText(str(ans))
        except:
            self.label.setText("wrong input")
    def method_dot(self):
        text=self.label.text()
        self.label.setText(text+".")
    def method_clear(self):
        text=self.label.text()
        self.label.setText("")
    def method_del(self):
        text=self.label.text()
        self.label.setText(text[:len(text)-1])
    
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
